[package]
name = "parking_lot"
version = "0.5.5"
authors = ["Amanieu d'Antras <amanieu@gmail.com>"]
description = "More compact and efficient implementations of the standard synchronization primitives."
documentation = "https://amanieu.github.io/parking_lot/parking_lot/index.html"
license = "Apache-2.0/MIT"
repository = "https://github.com/Amanieu/parking_lot"
readme = "README.md"
keywords = ["mutex", "condvar", "rwlock", "once", "thread"]

[dependencies]
parking_lot_core = { path = "core", version = "0.2" }
parking_lot_wrappers = { path = "wrappers", version = "0.1" }

[dev-dependencies]
rand = "0.4"

[features]
default = ["owning_ref"]
owning_ref = ["parking_lot_wrappers/owning_ref"]
nightly = ["parking_lot_core/nightly"]
deadlock_detection = ["parking_lot_core/deadlock_detection"]

[workspace]
exclude = ["benchmark"]
